#!/usr/bin/env python
# coding: utf-8

# # DATA SALES✨

# In[1]:


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


# In[2]:


data =pd.read_csv('C:/Users/Oooba/Desktop/Analysis with pyhton/intern2grow/sales_data.csv')
data


# # Data cleaning 

# In[3]:


data.info()


# In[6]:


data.isna().sum()


# In[7]:


x=data['price'].mean()
y=data["quantity"].mean()
z=data['revenue'].mean()
x ,y,z


# In[8]:


data['price']= data['price'].fillna(x)
data['quantity']= data['quantity'].fillna(y)
data['revenue']= data['revenue'].fillna(z)
data.isna().sum()


# In[9]:


data.duplicated().sum()


# In[10]:


data=data.drop_duplicates()


# In[11]:


data.describe()


# # DATA ANALYSIS

# # Q1:What was the total revenue generated by the company over the course of the year?

# In[12]:


Total_Revenue=data['revenue'].sum()
print("The Total Revenue =",Total_Revenue,"$")


# # Q2: Which product had the highest revenue? How much revenue did it generate?

# In[13]:


Proudct_Rev =data.groupby('product')['revenue'].sum().sort_values(ascending=False).head(7)
Proudct_Rev


# In[14]:


from matplotlib import style
style.use("bmh")
plt.figure (facecolor="white")
Proudct_Rev.plot(kind="bar",color='brown')
plt.title("Top Product Revenues ")
plt.xlabel("Product")
plt. ylabel("Revenue")
plt.grid(True)
plt.show()
print("The Top product is Smartphone by Revenue 434400$")


# # Q3:What was the average price of a product sold by the company?

# In[15]:


Price_AVG =data.groupby('product')["price"].mean().sort_values(ascending=False).reset_index()
Price_AVG.columns=['Product','AVG Price']
Price_AVG


# # Q4:What was the total quantity of products sold by the company?

# In[16]:


Total_quantity =data['quantity'].sum()
print("The Total Ouantity of Product =", Total_quantity)


# # Q5:Which category had the highest revenue? How much revenue did it generate?

# In[17]:


category_Rev =data.groupby('category')['revenue'].sum().sort_values(ascending=False)
category_Rev


# In[30]:


category_Rev.plot(kind="bar",color='brown')
plt.title(" Revenues by Category ")
plt.xlabel("category")
plt. ylabel("Revenue")
plt.grid(True)
plt.show()
print("The Top category is Electronics  by Revenue 516080$")


# # Q6:What was the average revenue per sale?

# In[4]:


Sales_avg_Rev =data.groupby('date')['revenue'].sum().sort_values(ascending=False).reset_index()


# In[19]:


plt.plot(Sales_avg_Rev['date'],Sales_avg_Rev['revenue'],marker="*",color="brown")
plt.title(" Average Revenue per Sale ")
plt.xlabel("Date")
plt. ylabel("Revenue")
plt.grid(True)
plt.show()


# # Q7:What was the total revenue generated in each quarter of the year? (i.e. Q1, Q2, Q3, Q4)

# In[26]:


import datetime as dt
data['date'] = pd.to_datetime(data['date'],  infer_datetime_format=True)
data["Q"]=data["date"].dt.quarter
Quarter_Rev =data.groupby('Q')['revenue'].sum()
Quarter_Rev


# In[29]:


Quarter_Rev.plot(kind="bar",color='brown')
plt.title(" Revenues by  Quarter ")
plt.xlabel("Quarter")
plt. ylabel("Revenues")
plt.grid(True)
plt.show()

